=encoding utf8

=head1 The CPAN

Z<cpan>

Perl 5 е прагматичен език сам по себе си, само че още по-прагматичните членове на Perl
общността са развили тази идея и са публикували плодовете на своите усилия за ползване от всички. 
Ако имате задача за решаване, много е възможно, някой вече да е написал и споделил кода за решаването й.

X<CPAN>

При съвременното програмиране на Perl се използва преди всичко мрежата от архиви CPAN (U<http://www.cpan.org/>).
Мрежата от архиви (The Comprehensive Perl Archive Network) е система за качване и сваляне (ъплоуд и мирорване)
на код. Тази мрежа е един от най-големите --ако не I<най>--големият архив на библиотеки от код в целия свят.
CPAN съдържа библиотеки за всичко, от работа с бази данни, до протоколи за всякакви мрежови устройства, до работа със 
звукови и видео библиотеки, както и за работа със споделени библиотеки инсталирани на вашата система.

Без архивите CPAN, Perl се превръща просто в поредният език за програмиране. Програмирането на Perl с използване на 
CPAN е просто невероятно.

X<distribution>
X<modules>

CPAN предоставя чрез мироринг I<дистрибуции>, така се наричат сборници с Perl код, готови за употреба. В дадена 
дистрибуция се съдържат един или повече I<модули>, така се наричат завършени библиотеки от Perl код. 
Всяка дистрибуция си има запазено наименование в CPAN и съдържа свои уникални мета-данни.

=begin tip Мрежата от архиви CPAN е огромна, Наистина Огромна.

Мрежата от архиви CPAN I<добавя>, всеки месец, стотици регистрирани разработчици, които допринасят хиляди 
индексирани модула, групирани в хиляди дистрибуции. При това тези цифри не включват актуализациите на 
вече съществуващи части.
Към края на Ноември 2011, search.cpan.org наброяваше 9359 отделни човека, които качват съдържание, 
101656 модула, и 23808 дистрибуции ( това представлява нарастване с  11.5%, 19.4%, и 14.3% респективно, 
взето в сравнение с времето на предишното издание на тази книга).

=end tip

X<search.cpan.org>

Самата мрежа CPAN е просто мироринг система. Авторите качват своите дистрибуции и CPAN ги препраща към мирор страници, 
от които потребителите и CPAN клиенти ги - свалят, конфигурират, изграждат, проверяват, и инсталират. 
Системата е успешна благодарение, както на тази простота, така също и на приноса на хиляди доброволци,
които надграждат на базата на тази система за разпространение.
В частност, стандартите възприети от общността са развити до толкова, че да идентифицират атрибутите и характеристиките
на добре формулираните CPAN дистрибуции.
Това включва:

=over 4

=item * Стандарти за автоматични CPAN инсталатори.

=item * Стандарти за това, как точно мета-данните да описват какво предоставя и изисква всяка дистрибуция.

=item * Стандарти за документиране и лицензиране.

=back

Допълнителни CPAN възможности осигуряват автоматизирани проверки и отчети, които да подобряват качеството
при създаване на пакети и перносимостта между различните платформи и версии на Perl. 
Всяка новосъздадена CPAN дистрибуция получава своя опашка на U<http://rt.cpan.org/> 
за записване и отчет на грешките и съвместна работа с авторите. Страниците на CPAN осигуряват връзка 
и с предишните версии на дадена дистрибуция, класации на модулите, документация, бележки и още много информация.
Всичко това е на ваше разположение на U<http://search.cpan.org/>.

X<CPAN; C<CPAN.pm>>
X<CPAN; C<CPANPLUS>>

Modern Perl installations include two clients to connect to, search, download,
build, test, and install CPAN distributions, CPAN.pm and CPANPLUS. For the most
part, each of these clients is equivalent for basic installation. This book
recommends the use of CPAN.pm solely due to its ubiquity. With a recent version
(as of this writing, 1.9800 is the latest stable release), module installation
is reasonably easy. Start the client with:

=begin screen

    $ B<cpan>

=end screen

To install a distribution within the client:

=begin screen

    $ B<cpan>
    cpan[1]> B<install Modern::Perl>

=end screen

... or to install directly from the command line:

=begin screen

    $ B<cpan Modern::Perl>

=end screen

X<CPAN; C<CPAN.pm>>

Eric Wilhelm's tutorial on configuring
CPAN.pmN<U<http://learnperl.scratchcomputing.com/tutorials/configuration/>>
includes a great troubleshooting section.

=begin sidebar

Even though the CPAN client is a core module for the Perl 5 distribution, you
will likely need to install standard development tools such as a C<make>
utility and possibly a C compiler. Windows users, see Strawberry Perl
(U<http://strawberryperl.com/>) and Strawberry Perl Professional. Mac OS X
users must install XCode. Unix and Unix-like users often have these tools
available (though Debian and Ubuntu users should install C<build-essential>).

=end sidebar

=head2 CPAN Management Tools

If your operating system provides its own installation of Perl 5, that version
may be out of date or it may have its own dependencies on specific versions of
CPAN distributions. Serious Perl developers often construct virtual walls
between the system Perl and their development Perl installations. Several
projects help to make this possible.

C<App::cpanminus> is a relatively new CPAN client with goals of speed,
simplicity, and zero configuration. Install it with C<cpan App::cpanminus>, or:

=begin screen

    $ B<curl -LO http://xrl.us/cpanm>
    $ B<chmod +x cpanm>

=end screen

C<App::perlbrew> is a system to manage and to switch between your own
installations of multiple versions and configurations of Perl. Installation is
as easy as:

=begin screen

    $ B<curl -LO http://xrl.us/perlbrew>
    $ B<chmod +x perlbrew>
    $ B<./perlbrew install>
    $ B<perldoc App::perlbrew>

=end screen

X<CPAN; local::lib>
X<CPAN; App::local::lib::helper>

The C<local::lib> CPAN distribution allows you to install and to manage
distributions in your own user directory, rather than for the system as a
whole. This is an effective way to maintain CPAN distributions without
affecting other users. Installation is somewhat more involved than the previous
two distributions, though C<App::local::lib::helper> can simplify the process.  See
U<http://search.cpan.org/perldoc?local::lib> and
U<http://search.cpan.org/perldoc?App::local::lib::helper> for more details.

All three projects tend to assume a Unix-like environment (such
as a GNU/Linux distribution or even Mac OS X). Windows users, see the Padre
all-in-one download (U<http://padre.perlide.org/download.html>).
